targets:
  $default:
    builders:
      drift_dev:
        options:
          named_parameters: true
          sql:
            dialect: sqlite
            options:
              version: "3.38"
              modules: [fts5]