name: maple_common
description: Common package for Maple.
version: 0.0.1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  app_links: ^3.4.3
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.7.1
  collection: ^1.17.1
  dart_jsonwebtoken: ^2.8.0
  device_info_plus: ^10.0.1
  diacritic: ^0.1.3
  drift: ^2.11.0
  easy_debounce: ^2.0.3
  easy_localization: ^3.0.2
  email_validator: ^2.1.17
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.6
  firebase_dynamic_links: ^5.0.11
  firebase_messaging: ^14.7.20
  firebase_storage: ^11.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_google_street_view: ^3.1.3
  flutter_inappwebview: ^5.8.0
  flutter_local_notifications: ^17.0.0
  flutter_mobx: ^2.0.6+5
  flutter_signature_pad: ^3.0.1
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  get_it: ^7.6.0
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_flutter: ^2.3.0
  google_maps_flutter_platform_interface: 2.4.3
  google_place: ^0.4.7
  http: ^0.13.4
  image: ^4.1.3
  image_painter: ^0.6.1
  image_picker: ^1.0.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  location: ^5.0.1
  markdown: ^7.1.0
  mime: ^1.0.4
  mobx: ^2.2.0
  number_text_input_formatter: ^1.0.0+7
  open_filex: ^4.3.2
  package_info_plus: ^4.0.2
  path: ^1.8.2
  path_provider: ^2.0.15
  pdf: ^3.10.4
  printing: ^5.11.0
  provider: ^6.0.5
  pull_down_button: ^0.9.1
  rxdart: ^0.27.7
  sanitize_filename: ^1.0.5
  sembast: ^3.4.6+1
  timezone: ^0.9.2
  transparent_image: ^2.0.1
  uuid: ^4.2.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  analyzer: ^5.11.1
  build_runner: ^2.4.6
  drift_dev: ^2.13.1
  mobx_codegen: ^2.3.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: CupertinoIcons
      fonts:
        - asset: assets/fonts/Cupertino-Icons.ttf
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
